server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: service-eureka
          uri: https://github.com/RECAVERO/service-customer-mongo
          search-paths: config-data
  application:
    name: config-service
